apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: infiscal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: infisical-frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resources:
      name: cpu
      targetAverageUtilization: 80  
  